include: package:very_good_analysis/analysis_options.5.0.0.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**.g.dart

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
