# FAQ: https://github.com/dart-lang/build/blob/master/docs/faq.md
targets:
  $default:
    builders:
      retrofit_generator:
        generate_for:
          - lib/api/*.dart
          - lib/api/**/*.dart
      drift_dev:
        generate_for:
          - lib/database/*.dart
          - lib/database/**/*.dart