name: sputnikn_chat_client
description: SputnikN Websocket chat client
version: 0.0.1
author: Alex Shniperson
publish_to: none

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  protobuf: ^3.1.0
  drift: ^2.13.0
  sqlite3: ^2.1.0
  retrofit: ^4.0.3
  http: ^1.1.0
  dio: ^5.3.3
  mime: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.0
  retrofit_generator: ^8.0.2
  test: ^1.24.9
  very_good_analysis: ^5.1.0
