name: sputnikn_chat_client
description: SputnikN Websocket chat client
version: 0.0.1
author: Alex Shniperson
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  protobuf: ^2.0.1
  drift: 1.0.1
  sqlite3: ^1.3.1
  retrofit: ^3.0.0
  http: ^0.13.4
  dio: ^4.0.4
  mime: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.5
  drift_dev: 1.0.2
  retrofit_generator: ^3.0.0+2
  test: ^1.19.5
